name: Create archive and release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor
        release_branches: main
    - name: Install zip
      uses: montudor/action-zip@v1
    - name: Archive
      run: zip -qq -r cbas+.zip .
      working-directory: cbas+
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          cbas+/cbas+.zip
          yoda-launcher.bat
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
