name: Create archive and release
on:
  push:
    branches:
      - main
      - archive2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor
        release_branches: main
    - name: Log
      run: |
        ls .
        ls cbas+/
    - name: Archive
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r test.zip .
        working-directory: cbas+
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: test.zip
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
