name: Create Archive
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'cbas+.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "cbas+.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
