name: Create archive and release
on:
  [push]
  # push:
  #   branches:
  #     - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor
    - name: Archive
      uses: thedoctor0/zip-release@master
      with:
        filename: 'cbas+.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: cbas+.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
