name: Create archive and release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        default_bump: minor
        release_branches: main
    - name: Log
      run: |
        ls .
        ls cbas+/assets/minecraft/optifine/cit/icons/cbas
    - name: Archive
      uses: thedoctor0/zip-release@master
      with:
        filename: 'cbas+.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
        directory: cbas+/
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: cbas+.zip
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
